export const PERMISSION_CODES = {
  ORG_READ: 'ORG_READ',
  ORG_MANAGE: 'ORG_MANAGE',
  PERSONNEL_READ: 'PERSONNEL_READ',
  PERSONNEL_SELF_READ: 'PERSONNEL_SELF_READ',
  PERSONNEL_SENSITIVE_READ: 'PERSONNEL_SENSITIVE_READ',
  PERSONNEL_MANAGE: 'PERSONNEL_MANAGE',
  PAY_STRUCTURE_READ: 'PAY_STRUCTURE_READ',
  PAY_STRUCTURE_SELF_READ: 'PAY_STRUCTURE_SELF_READ',
  PAY_STRUCTURE_MANAGE: 'PAY_STRUCTURE_MANAGE',
  APPROVALS_READ: 'APPROVALS_READ',
  APPROVALS_SELF_READ: 'APPROVALS_SELF_READ',
  APPROVALS_APPROVE: 'APPROVALS_APPROVE',
  APPROVALS_MANAGE: 'APPROVALS_MANAGE',
  RBAC_READ: 'RBAC_READ',
  RBAC_MANAGE: 'RBAC_MANAGE',
} as const;

export type PermissionCode =
  (typeof PERMISSION_CODES)[keyof typeof PERMISSION_CODES];

export const PERMISSIONS_KEY = 'permissions';

export const DOMAIN_PERMISSION_DEFAULTS = {
  'org-structure': {
    read: PERMISSION_CODES.ORG_READ,
    write: PERMISSION_CODES.ORG_MANAGE,
  },
  personnel: {
    read: PERMISSION_CODES.PERSONNEL_READ,
    write: PERMISSION_CODES.PERSONNEL_MANAGE,
  },
  'pay-structure': {
    read: PERMISSION_CODES.PAY_STRUCTURE_READ,
    write: PERMISSION_CODES.PAY_STRUCTURE_MANAGE,
  },
  approvals: {
    read: PERMISSION_CODES.APPROVALS_READ,
    write: PERMISSION_CODES.APPROVALS_MANAGE,
  },
  rbac: {
    read: PERMISSION_CODES.RBAC_READ,
    write: PERMISSION_CODES.RBAC_MANAGE,
  },
} as const satisfies Record<
  string,
  { readonly read: PermissionCode; readonly write: PermissionCode }
>;
